inherit_gem:
  standard: config/base.yml
plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false