name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
          - 3.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snickerbockers/submodules-init@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Install dependencies
        run: bundle install --without dev lint
      - name: Run tests
        run: bundle exec rake
